config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :bulk_product_edits do

      get 'product_details', to: 'bulk_product_edits#product_details'
      post 'product_details', to: 'bulk_product_edits#product_details_update'

      get 'review_updates', to: 'bulk_product_edits#review_updates'
      get 'update_products', to: 'bulk_product_edits#update_products'

      resources :bulk_product_edit_properties do
        collection do
          post :update_positions
        end
      end

      resources :bulk_product_edit_items do
        collection do
          get 'select_by_taxon', to: 'bulk_product_edit_items#index', defaults: { select_by: 'taxon' }
          get 'select_by_sku', to: 'bulk_product_edit_items#index', defaults: { select_by: 'sku' }
        end
      end

      resources :bulk_product_edit_order_info_items, only: [:index]

    end

    resources :bulk_product_spreadsheet_edits
  end

  namespace :api do
    namespace :v1 do
      get 'bulk_product_edit_items/products_for_selection', to: 'bulk_product_edit_items#products_for_selection', defaults: { format: 'json' }
    end
  end
end

app/models/spree/bulk_product_edit.rb
module Spree
  class BulkProductEdit < Spree::Base

    PRODUCT_DETAILS_FIELDNAMES = %w[
      master_price
      product_price
      sample_price
      available_on
      expires_on
      weight
      height
      width
      depth
      sale_unit_id
      country_of_origin
    ]

    has_many :bulk_product_edit_items, dependent: :destroy

    has_many :bulk_product_edit_properties, dependent: :destroy, inverse_of: :bulk_product_edit
    has_many :properties, through: :bulk_product_edit_properties

    has_and_belongs_to_many :order_info_items, :uniq => true, :join_table => :spree_bulk_product_edits_order_info_items

    accepts_nested_attributes_for :bulk_product_edit_properties, allow_destroy: true, reject_if: lambda { |pp| pp[:property_name].blank? }

    self.whitelisted_ransackable_attributes =  %w[created_at]

    validates :name, presence: true

    def set_order_info_item name
      item = Spree::OrderInfoItem.find_by(name: name)
      self.order_info_items << item unless item.nil? || self.order_info_items.include?(item)
    end

  end
end

app/controllers/spree/admin/bulk_product_edits_controller.rb
module Spree
  module Admin
    class BulkProductEditsController < ResourceController

      include ProductHelper
      include ActionController::Live
      require 'json'

      update.before :update_before
      before_action :get_bulk_product_edit, only: [:product_details, :review_updates, :update_products]

      def index
        respond_with(@collection)
      end

      def product_details
        @sale_units = Spree::SaleUnit.order(:name)
        @countries = Spree::Country.all
      end

      def review_updates
        @products = products
        @details = extract_product_details
        @order_info_items = @bulk_product_edit.order_info_items
        @properties = @bulk_product_edit.bulk_product_edit_properties
      end

      def update_products
        products.each do |product|
          set_product_details product
          set_product_ordering_information product
          set_product_properties product
        end

        # flash[:success] = 'Products updated'
        # redirect_to location_after_save

        response.headers['Content-Type'] = 'text/event-stream'

        item = { status: 'Products updated' }
        response.stream.write 'event: update'+$/
        response.stream.write 'data: '+item.to_json+$/+$/

      rescue IOError
        # client disconnected.
      ensure
        response.stream.close
      end

      private

      def get_bulk_product_edit
        @bulk_product_edit = Spree::BulkProductEdit.find(params[:bulk_product_edit_id])
      end

      def location_after_save
        return admin_bulk_product_edit_product_details_path(@bulk_product_edit) if params['update_product_details'].present?
        return admin_bulk_product_edit_bulk_product_edit_order_info_items_path(@bulk_product_edit) if params['update_ordering_information'].present?
        return admin_bulk_product_edit_bulk_product_edit_properties_path(@bulk_product_edit) if params['update_product_properties'].present?

        return edit_admin_bulk_product_edit_path(@bulk_product_edit)
      end

      def permitted_resource_params
        params.require(:bulk_product_edit)
            .permit(:id, :name, :master_price, :product_price, :sample_price, :available_on, :expires_on,
                :weight, :height, :width, :depth, :sale_unit_id, :country_of_origin,
                :clear_details, :clear_ordering_information, :clear_properties,
                order_info_item_ids: [],
                bulk_product_edit_properties_attributes: [:id, :property_name, :value])
      end

      def collection
        return @collection if @collection.present?

        params[:q] ||= {}

        params[:q][:s] ||= 'created_at desc'
        @collection = super

        @search = @collection.ransack(params[:q])
        @collection = @search.result.
            page(params[:page]).
            per(params[:per_page] || SpreeBulkProductEdit.configuration.admin_edits_per_page)
        @collection
      end

      def update_before
        # note: we only reset the bulk product edit properties if we're receiving a post from the form on that tab
        return unless params[:clear_bulk_product_edit_properties]
        params[:bulk_product_edit] ||= {}
      end

      def products
        product_ids = Spree::BulkProductEditItem.where(bulk_product_edit_id: params[:bulk_product_edit_id]).pluck(:product_id)
        Spree::Product.where(id: product_ids)
      end

      def extract_product_details
        details = {}
        Spree::BulkProductEdit::PRODUCT_DETAILS_FIELDNAMES.each do |fieldname|
          details[fieldname.to_sym] = @bulk_product_edit.send(fieldname.to_sym) if @bulk_product_edit.send(fieldname.to_sym).present?
        end

        if details[:sale_unit_id].present?
          details[:sale_unit] = Spree::SaleUnit.find(details[:sale_unit_id]).name
          details.delete(:sale_unit_id)
        end

        if details[:country_of_origin].present?
          details[:country_of_origin] = Spree::Country.find(details[:country_of_origin]).name
        end

        details
      end

      def set_product_details product
        product.master.price = @bulk_product_edit.master_price if @bulk_product_edit.master_price.present?

        product.variants.each do |variant|
          if variant_is_sample(variant)
            variant.price = @bulk_product_edit.sample_price if @bulk_product_edit.sample_price.present?
          else
            variant.price = @bulk_product_edit.product_price if @bulk_product_edit.product_price.present?
          end

          variant.weight = @bulk_product_edit.weight if @bulk_product_edit.weight.present?
          variant.height = @bulk_product_edit.height if @bulk_product_edit.height.present?
          variant.width = @bulk_product_edit.width if @bulk_product_edit.width.present?
          variant.depth = @bulk_product_edit.depth if @bulk_product_edit.depth.present?

          variant.save!
        end

        product.available_on = @bulk_product_edit.available_on if @bulk_product_edit.available_on.present?
        product.expires_on = @bulk_product_edit.expires_on if @bulk_product_edit.expires_on.present?

        product.sale_unit_id = @bulk_product_edit.sale_unit_id if @bulk_product_edit.sale_unit_id.present?
        product.country_of_origin = @bulk_product_edit.country_of_origin if @bulk_product_edit.country_of_origin.present?

        product.save!
      end

      def set_product_ordering_information product
        product.order_info_items = [] if @bulk_product_edit.clear_ordering_information
        @bulk_product_edit.order_info_items.each do |item|
          product.order_info_items << item unless product.order_info_items.include? item
        end
        product.save!
      end

      def set_product_properties product
        product.properties = [] if @bulk_product_edit.clear_properties
        @bulk_product_edit.bulk_product_edit_properties.each do |bulk_product_edit_property|
          product.set_property(bulk_product_edit_property.property.name, bulk_product_edit_property.value)
        end
        product.save!
      end

    end
  end
end

app/views/spree/admin/bulk_product_edits/_form.html.erb
<%= f.field_container :name, class: ['form-group'] do %>
    <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
    <%= f.text_field :name, :required => true, :class => 'form-control' %>
<% end %>

app/views/spree/admin/bulk_product_edits/edit.html.erb
<%= render partial: 'spree/admin/shared/bulk_product_edits_tabs', locals: { current: :details } %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @bulk_product_edit } %>


<%= form_for( [:admin, @bulk_product_edit] )do |f| %>
    <fieldset data-hook="bulk_product_edit">
      <%= render partial: 'form', locals: { f: f } %>
    </fieldset>
    <div class="form-actions">
      <%= render partial: 'spree/admin/shared/edit_resource_links' %>
    </div>
<% end %>

app/views/spree/admin/bulk_product_edits/index.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:bulk_product_edit) %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:new) + ' ' + Spree.t(:bulk_product_edit), new_object_url, { :class => 'btn-success', :icon => 'add', 'data-update' => 'new_bulk_product_edit', :id => 'new_bulk_product_edit_link' } %>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

<% if @collection.any? %>
    <table class="table" id='bulk_product_edits' data-hook>
      <thead>
        <tr data-hook="bulk_product_edits_header">
          <th class="name"><%= Spree.t(:name) %></th>
          <th class="created_at"><%= Spree.t(:created_at) %></th>
          <th class="actions"></th>
        </tr>
      </thead>

      <tbody>
        <% @collection.each do |bulk_product_edit| %>
          <tr>
            <td class="name"><%= bulk_product_edit.name %></td>
            <td class="created_at"><%= bulk_product_edit.created_at.to_date %></td>
            <td class="actions actions-2 text-right">
              <%= link_to_edit(bulk_product_edit, :no_text => true) %>
              <%= link_to_delete(bulk_product_edit, :no_text => true) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::BulkProductEdit)) %>,
      <%= link_to Spree.t(:add_one), new_object_url %>!
    </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

app/views/spree/admin/bulk_product_edits/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @product_import } %>

<% content_for :page_title do %>
    <%= Spree.t(:new) + ' ' + Spree.t(:bulk_product_edit) %>
<% end %>

<%= form_for( [:admin, @bulk_product_edit] )do |f| %>
    <fieldset data-hook="bulk_product_edit">
      <%= render partial: 'form', locals: { f: f } %>
    </fieldset>
    <div class="form-actions">
      <%= render partial: 'spree/admin/shared/new_resource_links' %>
    </div>
<% end %>

app/views/spree/admin/bulk_product_edits/product_details.html.erb
<%= render partial: 'spree/admin/shared/bulk_product_edits_tabs', locals: { current: :product_details } %>

<%= form_for( [:admin, @bulk_product_edit] )do |f| %>
  <div data-hook="admin_bulk_product_edit_form_fields">
    <%= hidden_field_tag 'update_product_details', 1 %>

    <div class="row">

      <div class="col-md-4">
        <div data-hook="admin_bulk_product_edit_form_master_price">
          <%= f.field_container :master_price, class: ['form-group'] do %>
              <%= f.label :master_price, Spree.t(:master_price) %>
              <%= f.text_field :master_price, class: 'form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_bulk_product_edit_form_product_price">
          <%= f.field_container :product_price, class: ['form-group'] do %>
              <%= f.label :product_price, Spree.t(:product_price) %>
              <%= f.text_field :product_price, class: 'form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_bulk_product_edit_form_sample_price">
          <%= f.field_container :sample_price, class: ['form-group'] do %>
              <%= f.label :sample_price, Spree.t(:sample_price) %>
              <%= f.text_field :sample_price, class: 'form-control' %>
          <% end %>
        </div>
      </div>

      <div class="col-md-4">
        <div data-hook="admin_bulk_product_edit_form_available_on">
          <%= f.field_container :available_on, class: ['form-group'] do %>
              <%= f.label :available_on, Spree.t(:available_on) %>
              <%= f.text_field :available_on, class: 'datepicker form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_bulk_product_edit_form_expires_on">
          <%= f.field_container :expires_on, class: ['form-group'] do %>
              <%= f.label :expires_on, Spree.t(:expires_on) %>
              <%= f.text_field :expires_on, class: 'datepicker form-control' %>
          <% end %>
        </div>
      </div>

      <div class="col-md-4">
        <div data-hook="admin_bulk_product_edit_form_weight">
          <%= f.field_container :weight, class: ['form-group'] do %>
              <%= f.label :weight, Spree.t(:weight) %>
              <%= f.text_field :weight, class: 'form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_bulk_product_edit_form_height">
          <%= f.field_container :height, class: ['form-group'] do %>
              <%= f.label :height, Spree.t(:height) %>
              <%= f.text_field :height, class: 'form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_bulk_product_edit_form_width">
          <%= f.field_container :width, class: ['form-group'] do %>
              <%= f.label :width, Spree.t(:width) %>
              <%= f.text_field :width, class: 'form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_bulk_product_edit_form_depth">
          <%= f.field_container :depth, class: ['form-group'] do %>
              <%= f.label :depth, Spree.t(:depth) %>
              <%= f.text_field :depth, class: 'form-control' %>
          <% end %>
        </div>
      </div>

    </div>

    <div class="row">

      <div class="col-md-4">
        <div data-hook="admin_bulk_product_edit_form_sale_unit">
          <%= f.field_container :sale_unit, class: ['form-group'] do %>
              <%= f.label :sale_unit, Spree.t(:sale_unit) %>
              <%= f.collection_select(:sale_unit_id, @sale_units, :id, :name, { include_blank: true }, { class: 'form-control' }) %>
          <% end %>
        </div>

        <div data-hook="admin_bulk_product_edit_form_country_of_origin">
          <%= f.field_container :country_of_origin, class: ['form-group'] do %>
              <%= f.label :country_of_origin, Spree.t(:country_of_origin) %>
              <%= f.collection_select(:country_of_origin, @countries, :id, :name, { include_blank: true }, { class: 'form-control' }) %>
          <% end %>
        </div>
      </div>


    </div>
  </div>

  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.update'), 'ok', 'submit', {class: 'btn-success', data: { disable_with: "#{ Spree.t(:saving) }..." }} %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= button_link_to Spree.t('actions.cancel'), admin_bulk_product_edits_url, icon: 'remove' %>
  </div>
<% end %>

app/views/spree/admin/bulk_product_edits/review_updates.html.erb
<%= render partial: 'spree/admin/shared/bulk_product_edits_tabs', locals: { current: :review_updates } %>

<div class="row bulk_product_edit_overview">
  <div class="col-md-12">

    <div id="notice"></div>


    <div class="well well-lg">
      The following updates will be applied to the selected products:
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Selected Products</h3>
      </div>
      <div class="panel-body">
      <% if @products.any? %>
            <div class="list-group">
              <% @products.each do |product| %>
                  <a href="/products/<%= product.slug %>" target="_blank" class="list-group-item">
                    <%= mini_image product %>
                    <h4 class="list-group-item-heading"><%= product.name %></h4>
                    <p class="list-group-item-text"><%= product.description %></p>
                  </a>
              <% end %>
            </div>
      <% else %>
          <p>No products</p>
      <% end %>
      </div>
    </div>

    <% if @details.any? %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Product Details</h3>
        </div>

        <table class="table">
          <thead>
          <tr>
            <th>Name</th>
            <th>Value</th>
          </tr>
          </thead>

          <tbody>
          <% @details.each do |key, value| %>
              <tr>
                <td><%= Spree.t(key) %></td>
                <td><%= value %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    <% end %>

    <% if @order_info_items.any? %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Ordering Information</h3>
        </div>

        <div class="panel-body">
          <% if @bulk_product_edit.clear_ordering_information %>
            <p>Existing ordering information will be deleted from the selected products, and the following items will be added:</p>
          <% else %>
            <p>Existing ordering information will be retained for each selected product, and the following items will be added or changed:</p>
          <% end %>
        </div>

        <table class="table">
          <thead>
          <tr>
            <th>Description</th>
          </tr>
          </thead>

          <tbody>
          <% @order_info_items.each do |item| %>
              <tr>
                <td><%= item.description.html_safe %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    <% end %>

    <% if @properties.any? %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Product Properties</h3>
        </div>

        <div class="panel-body">
          <% if @bulk_product_edit.clear_properties %>
            <p>Existing properties will be deleted from the selected products, and the following properties will be added:</p>
          <% else %>
            <p>Existing properties will be retained for each selected product, and the following properties will be added or changed:</p>
          <% end %>
        </div>

        <table class="table">
          <thead>
          <tr>
            <th>Name</th>
            <th>Value</th>
          </tr>
          </thead>

          <tbody>
          <% @properties.each do |property| %>
              <tr>
                <td><%= property.property.presentation %></td>
                <td><%= property.value %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    <% end %>

  </div>

</div>

<%#= form_tag admin_bulk_product_edit_update_products_path(@bulk_product_edit) do %>
<!--<div class="form-actions" data-hook="buttons">-->
  <%#= button Spree.t(:apply), 'refresh', 'submit', { class: 'btn-success' } %>
<!--</div>-->
<%# end %>

<div class="form-actions" data-hook="buttons">
  <%= button_link_to Spree.t(:apply), '', { icon: 'refresh', class: 'btn btn-success', id: 'btn-apply-updates' } %>
</div>