config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :bulk_product_edits do

      get 'product_details', to: 'bulk_product_edits#product_details'
      post 'product_details', to: 'bulk_product_edits#product_details_update'

      get 'review_updates', to: 'bulk_product_edits#review_updates'
      get 'update_products', to: 'bulk_product_edits#update_products'

      resources :bulk_product_edit_properties do
        collection do
          post :update_positions
        end
      end

      resources :bulk_product_edit_items do
        collection do
          get 'select_by_taxon', to: 'bulk_product_edit_items#index', defaults: { select_by: 'taxon' }
          get 'select_by_sku', to: 'bulk_product_edit_items#index', defaults: { select_by: 'sku' }
        end
      end

      resources :bulk_product_edit_order_info_items, only: [:index]

    end

    resources :bulk_product_spreadsheet_edits
  end

  namespace :api do
    namespace :v1 do
      get 'bulk_product_edit_items/products_for_selection', to: 'bulk_product_edit_items#products_for_selection', defaults: { format: 'json' }
    end
  end
end

app/models/spree/bulk_product_edit_property.rb
module Spree
  class BulkProductEditProperty < Spree::Base
    acts_as_list scope: :bulk_product_edit

    belongs_to :bulk_product_edit, touch: true, class_name: 'Spree::BulkProductEdit', inverse_of: :bulk_product_edit_properties
    belongs_to :property, class_name: 'Spree::Property', inverse_of: :bulk_product_edit_properties

    validates :property, presence: true

    validates_with Spree::Validations::DbMaximumLengthValidator, field: :value

    default_scope { order("#{self.table_name}.position") }

    self.whitelisted_ransackable_attributes = ['value']

    # virtual attributes for use with AJAX completion stuff
    def property_name
      property.name if property
    end

    def property_name=(name)
      if name.present?
        # don't use `find_by :name` to workaround globalize/globalize#423 bug
        property = Property.where(name: name).first || Property.create(name: name, presentation: name)
        self.property = property
      end
    end
  end
end

app/controllers/spree/admin/bulk_product_edit_properties_controller.rb
module Spree
  module Admin
    class BulkProductEditPropertiesController < ResourceController
      belongs_to 'spree/bulk_product_edit'

      # before_action :find_bulk_product_edit
      before_action :find_properties
      before_action :setup_property, only: :index

      private

      # def find_bulk_product_edit
      #   @bulk_product_edit = Spree::BulkProductEdit.find(params[:bulk_product_edit_id])
      # end

      def find_properties
        @properties = Spree::Property.pluck(:name)
      end

      def setup_property
        @bulk_product_edit.bulk_product_edit_properties.build
      end
    end
  end
end

app/views/spree/admin/bulk_product_edit_properties/index.html.erb
<%= render partial: 'spree/admin/shared/bulk_product_edits_tabs', locals: { current: :product_properties } %>

<%= form_for @bulk_product_edit, url: admin_bulk_product_edit_url(@bulk_product_edit), method: :put do |f| %>
    <%= hidden_field_tag 'update_product_properties', 1 %>

    <div class="row">
      <div class="col-md-12">

        <div class="panel panel-default">
          <div class="panel-body">
            <%= f.field_container :clear_properties, class: [''] do %>
                <%= f.label :clear_properties, value: true do %>
                    <%= f.radio_button :clear_properties, true %>
                    &nbsp; Clear all properties before adding only the values indicated here
                <% end %><br>
                <%= f.label :clear_properties, value: false do %>
                    <%= f.radio_button :clear_properties, false %>
                    &nbsp; Leave existing properties and add or update the values indicated here
                <% end %>
            <% end %>
          </div>
        </div>

      </div>
    </div>

    <fieldset>
      <div id="prototypes" data-hook></div>

      <table class="table sortable" data-hook data-sortable-link="<%= update_positions_admin_bulk_product_edit_bulk_product_edit_properties_url %>">
        <thead>
        <tr data-hook="bulk_product_edit_properties_header">
          <th colspan="2"><%= Spree.t(:property) %></th>
          <th><%= Spree.t(:value) %></th>
          <th class="actions"></th>
        </tr>
        </thead>

        <tbody id="bulk_product_edit_properties" data-hook>
        <%= f.fields_for :bulk_product_edit_properties, @bulk_product_edit.bulk_product_edit_properties do |ff| %>
            <tr class="bulk_product_edit_property fields" id="spree_<%= dom_id(ff.object) %>" data-hook="bulk_product_edit_property">
              <td class="move-handle">
                <% if ff.object.persisted? && can?(:edit, ff.object) %>
                <span class="icon icon-move handle"></span>
                <%= ff.hidden_field :id %>
                <% end %>
              </td>
              <td class='property_name'>
                <%= ff.text_field :property_name, class: 'autocomplete form-control' %>
              </td>
              <td class='value'>
                <%= ff.text_field :value, class: 'form-control' %>
              </td>
              <td class="actions actions-1">
                <% if ff.object.persisted? && can?(:destroy, ff.object) %>
                <%= link_to_delete ff.object, no_text: true %>
                <% end %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <div class="form-actions" data-hook="buttons">
        <%= button Spree.t('actions.update'), 'ok', 'submit', {class: 'btn-success', data: { disable_with: "#{ Spree.t(:saving) }..." }} %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= button_link_to Spree.t('actions.cancel'), admin_bulk_product_edits_url, icon: 'remove' %>
      </div>

      <%= hidden_field_tag 'clear_bulk_product_edit_properties', 'true' %>

    </fieldset>
<% end %>

<%= javascript_tag do %>
    var properties = <%= raw(@properties.to_json) %>;
    $('#bulk_product_edit_properties').on('keydown', 'input.autocomplete', function() {
      already_auto_completed = $(this).is('ac_input');
      if (!already_auto_completed) {
        $(this).autocomplete({source: properties});
        $(this).focus();
      }
    });
<% end %>