config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :bulk_product_edits do

      get 'product_details', to: 'bulk_product_edits#product_details'
      post 'product_details', to: 'bulk_product_edits#product_details_update'

      get 'review_updates', to: 'bulk_product_edits#review_updates'
      get 'update_products', to: 'bulk_product_edits#update_products'

      resources :bulk_product_edit_properties do
        collection do
          post :update_positions
        end
      end

      resources :bulk_product_edit_items do
        collection do
          get 'select_by_taxon', to: 'bulk_product_edit_items#index', defaults: { select_by: 'taxon' }
          get 'select_by_sku', to: 'bulk_product_edit_items#index', defaults: { select_by: 'sku' }
        end
      end

      resources :bulk_product_edit_order_info_items, only: [:index]

    end

    resources :bulk_product_spreadsheet_edits
  end

  namespace :api do
    namespace :v1 do
      get 'bulk_product_edit_items/products_for_selection', to: 'bulk_product_edit_items#products_for_selection', defaults: { format: 'json' }
    end
  end
end

app/models/spree/bulk_product_edit_item.rb
module Spree
  class BulkProductEditItem < Spree::Base

    #belongs_to :product
    belongs_to :bulk_product_edit

    validates :product_id, :bulk_product_edit_id, presence: true

  end
end

app/models/spree/property_decorator.rb
Spree::Property.class_eval do

  has_many :bulk_product_edit_properties, dependent: :delete_all, inverse_of: :property
  has_many :products, through: :bulk_product_edit_properties

end

app/controllers/spree/admin/bulk_product_edit_items_controller.rb
module Spree
  module Admin
    class BulkProductEditItemsController < ResourceController

      before_action :load_bulk_product_edit, except: [:create, :update]

      def index
        product_ids = Spree::BulkProductEditItem.where(bulk_product_edit: @bulk_product_edit).pluck(:product_id)
        @collection = Spree::Product.includes(master: [:images]).where(id: product_ids).order(:name)

        case params[:select_by]
          when 'taxon'
            render 'select_by_taxon'
          when 'sku'
            render 'select_by_sku'
          else
            render 'select_by_taxon'
        end
      end

      def create
        Spree::BulkProductEditItem.delete_all(bulk_product_edit_id: params[:bulk_product_edit_id])
        params[:product_ids].each do |id|
          Spree::BulkProductEditItem.create({ product_id: id, bulk_product_edit_id: params[:bulk_product_edit_id] })
        end if params[:product_ids].present?

        flash[:success] = 'Product list updated'

        case params[:select_by]
          when 'taxon'
            redirect_to select_by_taxon_admin_bulk_product_edit_bulk_product_edit_items_path params[:bulk_product_edit_id]
          when 'sku'
            redirect_to select_by_sku_admin_bulk_product_edit_bulk_product_edit_items_path params[:bulk_product_edit_id]
        end
      end

      private

      def load_bulk_product_edit
        @bulk_product_edit = Spree::BulkProductEdit.find(params[:bulk_product_edit_id])
      end

      def product_details
        details = {}
        details['product_price'] = params[:product_price] if is_number? params[:product_price]
        details['sample_price'] = params[:sample_price] if is_number? params[:sample_price]
        details['available_on'] = Date.strptime(params[:available_on], '%Y/%m/%d').to_time unless params[:available_on].nil?
        details['discontinue_on'] = Date.strptime(params[:discontinue_on], '%Y/%m/%d').to_time unless params[:discontinue_on].blank?
        details['weight'] = params[:weight] if is_number? params[:weight]
        details['height'] = params[:height] if is_number? params[:height]
        details['width'] = params[:width] if is_number? params[:width]
        details['depth'] = params[:depth] if is_number? params[:depth]
        details['sale_unit_id'] = params[:sale_unit_id] unless params[:sale_unit_id].blank?
        details['country_of_origin'] = params[:country_of_origin] unless params[:country_of_origin].blank?

        details
      end

      def is_number? string
        true if Float(string) rescue false
      end

    end
  end
end

app/controllers/spree/api/v1/bulk_product_edit_items_controller.rb
module Spree
  module Api
    module V1
      class BulkProductEditItemsController < Spree::Api::BaseController

        def products_for_selection

          case params[:select_by]
            when 'taxon'
              @new_products = products_by_taxon
            when 'sku'
             @new_products = products_by_sku
          end

          @selected_products = selected_products
          filter_new_products

          @products = (@new_products + @selected_products).sort! { |x, y| x['name'] <=> y['name'] }
          render json: { products: @products }
        end

        private

        def products_by_taxon
          taxon_ids = params[:identifiers]
          products = []
          Spree::Taxon.where(id: taxon_ids).each do |taxon|
            base_taxon_products = taxon.products.includes(master: [:images])
            children_taxon_products = taxon.children.includes(products: [master: [:images]]).map(&:products).flatten.compact.uniq
            products += (base_taxon_products + children_taxon_products).uniq
          end
          format_for_list products, false
        end

        def products_by_sku
          skus = params[:identifiers]
          products = Spree::Product.includes(master: [:images]).where(id: Spree::Variant.where(sku: skus).pluck(:product_id))
          format_for_list products, false
        end

        def selected_products
          bulk_product_edit_id = params[:bulk_product_edit_id]
          product_ids = Spree::BulkProductEditItem.where(bulk_product_edit_id: bulk_product_edit_id).pluck(:product_id)
          products = Spree::Product.includes(master: [:images]).where(id: product_ids)
          format_for_list products, true
        end

        def format_for_list products, selected
          out = []
          products.each do |p|
            attrs = p.attributes
            attrs[:sku] = p.master.sku
            attrs[:selected] = selected
            attrs[:thumbnail] = "https://dywimages.s3.amazonaws.com/spree/images/#{p.master.images[0].id}/mini/#{p.master.images[0].attachment_file_name}?#{rand(999999999)}"
            out << attrs
          end
          out
        end

        def filter_new_products
          @new_products.reject! { |p| in_selected? p }
        end

        def in_selected? product
          @selected_products.index { |s| s['id'] == product['id'] }
        end

      end
    end
  end
end

app/views/spree/admin/bulk_product_edit_items/_items_list_form.html.erb
<%= form_tag admin_bulk_product_edit_bulk_product_edit_items_path(@bulk_product_edit) do %>
    <%= hidden_field_tag 'select_by', select_by %>

    <table class="table" id="bulk_product_edit_items" data-hook>
      <thead>
      <tr id="bulk_product_edit_items_header" data-hook="bulk_product_edit_items_header">
        <th><%= check_box_tag 'all_product_ids', 'all', false, { id: 'product_ids_all' } %></th>
        <th class="product_id"><%= Spree.t(:product_id) %></th>
        <th class="sku"><%= Spree.t(:sku) %></th>
        <th class="image"><%= Spree.t(:thumbnail) %></th>
        <th class="name"><%= Spree.t(:name) %></th>
        <th class="actions"></th>
      </tr>
      </thead>

      <tbody id="bulk_product_edit_items_body">
      <% @collection.each do |item| %>
          <tr>
            <td><%= check_box_tag 'product_ids[]', item['id'], true, { id: "product_ids_#{item['id']}" } %></td>
            <td class="product_id"><%= item['id'] %></td>
            <td class="sku"><%= item.master['sku'] %></td>
            <td class="image"><%= mini_image item %></td>
            <td class="name"><%= item['name'] %>
            <td class="actions">
              <%= link_to_with_icon('eye-open', nil, product_url(item['id']), { :name => 'View', :no_text => true, :class => 'btn btn-primary btn-sm', :target => '_blank' }) %>
            </td>
          </tr>
      <% end unless @collection.nil? %>
      </tbody>
    </table>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.select'), 'ok', 'submit', {class: 'btn-success', data: { disable_with: "#{ Spree.t(:saving) }..." }} %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), admin_bulk_product_edits_url, icon: 'remove' %>
    </div>
<% end %>

app/views/spree/admin/bulk_product_edit_items/_select.js.erb
function setAllChecked() {
  $('#product_ids_all').prop('checked', ($('#bulk_product_edit_items_body input[type="checkbox"]:checked').length == $('#bulk_product_edit_items_body input[type="checkbox"]').length));
}

function getProductData(selectBy, identifiers) {
  $.ajax({
    url: '<%= api_v1_bulk_product_edit_items_products_for_selection_path %>',
    data: {
      bulk_product_edit_id: <%= @bulk_product_edit.id %>,
      select_by: selectBy,
      identifiers: identifiers,
      token: Spree.api_key
    },
    success: function(data) {
      populateRows(data)
    }
  });
}

function populateRows(data) {
  display_area = $('#bulk_product_edit_items_body');
  display_area.empty();
  if (data.products.length === 0) {
    // return display_area.html("<div class='alert alert-info'>" + Spree.translations.no_results + "</div>");
  } else {
    rows = formatRows(data.products);
    display_area.html(rows);
    setAllChecked();
    assignClickEventListener();
    //return;
  }
  return true;
}

function formatRows(products) {
  template = '<tr>' +
      '<td><input type="checkbox" name="product_ids[]" value="PRODUCT_ID"SELECTED></td>' +
      '<<td class="product_id">PRODUCT_ID</td>' +
      '<<td class="sku">PRODUCT_SKU</td>' +
      '<td class="image"><img src="PRODUCT_THUMBNAIL"></td>' +
      '<td class="name">PRODUCT_NAME</td>' +
      '<td class="actions"><a name="View" class="btn btn-primary btn-sm icon-link with-tip action-eye-open no-text" target="_blank" href="/products/PRODUCT_ID"><span class="icon icon-eye-open"></span> </a></td>' +
      '</tr>';

  rows = '';
  for (i = 0, len = products.length; i < len; i++) {
    rows +=  template.replace(/PRODUCT_ID/g, products[i]['id'])
        .replace(/SELECTED/, (products[i]['selected'] ? ' checked' : ''))
        .replace(/PRODUCT_SKU/, products[i]['sku'])
        .replace(/PRODUCT_THUMBNAIL/, products[i]['thumbnail'])
        .replace(/PRODUCT_NAME/, products[i]['name']);
  }
  return rows;
}

function assignClickEventListener() {
  // Dynamically inserted checkboxes don't have a click event, we have to look at the container
  $('#bulk_product_edit_items_body').on('click', ':checkbox', function(){
    if (!$(this).is(':checked')) {
      $('#bulk_product_edit_items_header').removeClass('order-selected');
      $('#bulk_product_edit_items_body tr').removeClass('order-selected');
      $(this).closest('tr').addClass('order-selected');
    } else {
      $(this).closest('tr').removeClass('order-selected');
    }
  });
}

$(function(){
  setAllChecked();

  $('#product_ids_all').click(function(){
    input_name = 'product_ids[]';
    $('input[name="'+input_name+'"]').prop('checked', $(this).is(':checked'));
  });

  // Dynamically inserted checkboxes don't have a click event, we have to look at the container
  $('#bulk_product_edit_items_body').on('click', ':checkbox', function() {
    setAllChecked();
  });

  <% if select_by == 'taxon' %>
    $('#product_taxon_ids').change(function(e){
      getProductData('taxon', e.val);
    });
  <% else %>
    $('#product_skus').change(function(){
      $(this).val($(this).val().replace(/\s+/g, ','));
      getProductData('sku', $(this).val().split(','));
    });
  <% end %>
});

app/views/spree/admin/bulk_product_edit_items/product_details_form.html.erb
<%= render partial: 'spree/admin/shared/bulk_product_edits_tabs', locals: { current: :product_details } %>

<%= form_for( [:admin, @bulk_product_edit] )do |f| %>
  <div data-hook="admin_bulk_product_edit_form_fields">

    <div class="row">

      <div class="col-md-4">
        <div data-hook="admin_bulk_product_edit_form_product_price">
          <%= f.field_container :product_price, class: ['form-group'] do %>
              <%= f.label :product_price, Spree.t(:product_price) %>
              <%= f.text_field :product_price, class: 'form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_bulk_product_edit_form_sample_price">
          <%= f.field_container :sample_price, class: ['form-group'] do %>
              <%= f.label :sample_price, Spree.t(:sample_price) %>
              <%= f.text_field :sample_price, class: 'form-control' %>
          <% end %>
        </div>
      </div>

      <div class="col-md-4">
        <div data-hook="admin_bulk_product_edit_form_available_on">
          <%= f.field_container :available_on, class: ['form-group'] do %>
              <%= f.label :available_on, Spree.t(:available_on) %>
              <%= f.text_field :available_on, class: 'datepicker form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_bulk_product_edit_form_discontinue_on">
          <%= f.field_container :discontinue_on, class: ['form-group'] do %>
              <%= f.label :discontinue_on, Spree.t(:discontinue_on) %>
              <%= f.text_field :discontinue_on, class: 'datepicker form-control' %>
          <% end %>
        </div>
      </div>

      <div class="col-md-4">
        <div data-hook="admin_bulk_product_edit_form_weight">
          <%= f.field_container :weight, class: ['form-group'] do %>
              <%= f.label :weight, Spree.t(:weight) %>
              <%= f.text_field :weight, class: 'form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_bulk_product_edit_form_height">
          <%= f.field_container :height, class: ['form-group'] do %>
              <%= f.label :height, Spree.t(:height) %>
              <%= f.text_field :height, class: 'form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_bulk_product_edit_form_width">
          <%= f.field_container :width, class: ['form-group'] do %>
              <%= f.label :width, Spree.t(:width) %>
              <%= f.text_field :width, class: 'form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_bulk_product_edit_form_depth">
          <%= f.field_container :depth, class: ['form-group'] do %>
              <%= f.label :depth, Spree.t(:depth) %>
              <%= f.text_field :depth, class: 'form-control' %>
          <% end %>
        </div>
      </div>

    </div>

    <div class="row">

      <div class="col-md-4">
        <div data-hook="admin_bulk_product_edit_form_sale_unit">
          <%= f.field_container :sale_unit, class: ['form-group'] do %>
              <%= f.label :sale_unit, Spree.t(:sale_unit) %>
              <%= f.collection_select(:sale_unit_id, @sale_units, :id, :name, { include_blank: true }, { class: 'form-control' }) %>
          <% end %>
        </div>

        <div data-hook="admin_bulk_product_edit_form_country_of_origin">
          <%= f.field_container :country_of_origin, class: ['form-group'] do %>
              <%= f.label :country_of_origin, Spree.t(:country_of_origin) %>
              <%= f.collection_select(:country_of_origin, @countries, :id, :name, { include_blank: true }, { class: 'form-control' }) %>
          <% end %>
        </div>
      </div>


    </div>
  </div>

  <div class="form-actions" data-hook="buttons">
    <%= button Spree.t('actions.update'), 'ok', 'submit', {class: 'btn-success', data: { disable_with: "#{ Spree.t(:saving) }..." }} %>
    <span class="or"><%= Spree.t(:or) %></span>
    <%= button_link_to Spree.t('actions.cancel'), admin_bulk_product_edits_url, icon: 'remove' %>
  </div>
<% end %>

app/views/spree/admin/bulk_product_edit_items/select_by_sku.html.erb
<%= render partial: 'spree/admin/shared/bulk_product_edits_tabs', locals: { current: :products_by_sku } %>

<script type="text/javascript">
  <%= render partial: 'spree/admin/bulk_product_edit_items/select', formats: :js, locals: { select_by: 'sku' } %>
</script>

<div class="form-group product_skus">
  <%= label_tag "bulk_product_edit_skus", Spree.t('enter_product_skus') %>
  <%= text_area_tag "bulk_product_edit[skus]", '', { id: 'product_skus', class: 'form-control' } %>
</div>

<%= render partial: 'spree/admin/bulk_product_edit_items/items_list_form', locals: { select_by: 'sku' } %>

app/views/spree/admin/bulk_product_edit_items/select_by_taxon.html.erb
<%= render partial: 'spree/admin/shared/bulk_product_edits_tabs', locals: { current: :products_by_taxon } %>

<script type="text/javascript">
  <%= render partial: 'spree/admin/bulk_product_edit_items/select', formats: :js, locals: { select_by: 'taxon' } %>
</script>

<div class="form-group taxons_rule_taxons">
  <%= label_tag "bulk_product_edit_taxon_ids_string", Spree.t('taxon_rule.choose_taxons') %>
  <%= hidden_field_tag "bulk_product_edit[taxon_ids_string]", '', class: "taxon_picker", id: 'product_taxon_ids' %>
</div>

<%= render partial: 'spree/admin/bulk_product_edit_items/items_list_form', locals: { select_by: 'taxon' } %>