config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :bulk_product_edits do

      get 'product_details', to: 'bulk_product_edits#product_details'
      post 'product_details', to: 'bulk_product_edits#product_details_update'

      get 'review_updates', to: 'bulk_product_edits#review_updates'
      get 'update_products', to: 'bulk_product_edits#update_products'

      resources :bulk_product_edit_properties do
        collection do
          post :update_positions
        end
      end

      resources :bulk_product_edit_items do
        collection do
          get 'select_by_taxon', to: 'bulk_product_edit_items#index', defaults: { select_by: 'taxon' }
          get 'select_by_sku', to: 'bulk_product_edit_items#index', defaults: { select_by: 'sku' }
        end
      end

      resources :bulk_product_edit_order_info_items, only: [:index]

    end

    resources :bulk_product_spreadsheet_edits
  end

  namespace :api do
    namespace :v1 do
      get 'bulk_product_edit_items/products_for_selection', to: 'bulk_product_edit_items#products_for_selection', defaults: { format: 'json' }
    end
  end
end

app/views/spree/admin/shared/_bulk_product_edits_tabs.html.erb
<% content_for :page_title do %>
    <%= link_to Spree.t(:bulk_product_edits), admin_bulk_product_edits_path %> / <%= @bulk_product_edit.name %>
<% end %>

<% content_for :sidebar do %>
    <ul class="nav nav-pills nav-stacked" data-hook="admin_product_import_tabs">
      <%= content_tag :li, class: ('active' if current == :details) do %>
          <%= link_to_with_icon 'edit', Spree.t(:details), spree.edit_admin_bulk_product_edit_url(@bulk_product_edit) %>
      <% end if can?(:admin, Spree::BulkProductEdit) %>

      <%= content_tag :li, class: ('active' if current == :products_by_taxon) do %>
          <%= link_to_with_icon 'th-large', Spree.t(:select_products_by_taxon), select_by_taxon_admin_bulk_product_edit_bulk_product_edit_items_path(@bulk_product_edit) %>
      <% end if can?(:admin, Spree::BulkProductEdit) %>

      <%= content_tag :li, class: ('active' if current == :products_by_sku) do %>
          <%= link_to_with_icon 'th-large', Spree.t(:select_products_by_sku), select_by_sku_admin_bulk_product_edit_bulk_product_edit_items_path(@bulk_product_edit) %>
      <% end if can?(:admin, Spree::BulkProductEdit) %>

      <%= content_tag :li, class: ('active' if current == :product_details) do %>
          <%= link_to_with_icon 'pushpin', Spree.t(:product_details), admin_bulk_product_edit_product_details_path(@bulk_product_edit) %>
      <% end if can?(:admin, Spree::BulkProductEdit) %>

      <%= content_tag :li, class: ('active' if current == :ordering_information) do %>
          <%= link_to_with_icon 'info-sign', Spree.t(:ordering_information), admin_bulk_product_edit_bulk_product_edit_order_info_items_path(@bulk_product_edit) %>
      <% end if can?(:admin, Spree::BulkProductEdit) %>

      <%= content_tag :li, class: ('active' if current == :product_properties) do %>
          <%= link_to_with_icon 'list-alt', Spree.t(:product_properties), admin_bulk_product_edit_bulk_product_edit_properties_path(@bulk_product_edit) %>
      <% end if can?(:admin, Spree::BulkProductEdit) %>

      <%= content_tag :li, class: ('active' if current == :review_updates) do %>
          <%= link_to_with_icon 'ok', Spree.t(:apply_changes), admin_bulk_product_edit_review_updates_path(@bulk_product_edit) %>
      <% end if can?(:admin, Spree::BulkProductEdit) %>
    </ul>
<% end %>